/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "part_c.h"


void
part_c_prog_1(char *host, char* path, char* outfile_name)
{
	CLIENT *clnt;
	outputData  *result_1;

	/**
		struct inputData{
			string path<>;
			string outfile_name<>;
			int a;
			int b;
		};
	**/
	inputData  part_c_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PART_C_PROG, PART_C_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	/* Set inputData struct appropriately to send to server*/
	part_c_1_arg.path = path;
	part_c_1_arg.outfile_name = outfile_name;
	/* Read input numbers from user and put into inputData*/
	scanf("%d %d", &part_c_1_arg.a, &part_c_1_arg.b);

	/* Call server's RPC function*/
	result_1 = part_c_1(&part_c_1_arg, clnt);

	/*open the output file*/
	FILE *output_file;
	output_file = fopen(part_c_1_arg.outfile_name, "a");
	
	if (result_1 == (outputData *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		if((*result_1).error){/* if server returned error as TRUE(1), write error message to file*/
			fprintf(output_file, "FAIL:\n%s", (*result_1).error_message);
			//printf("Error = %s \n", (*result_1).error_message);
		}
		else{/* if server returned error as FALSE(0), write result to file*/
			fprintf(output_file, "SUCCESS:\n%d\n", (*result_1).result);
			//printf("Result = %d \n", (*result_1).result);
		}
	}
	fclose(output_file);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s path outfile_name server_host\n", argv[0]);
		exit (1);
	}
	host = argv[3];
	part_c_prog_1 (host, argv[1],argv[2]);
exit (0);
}
