/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "part_c.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

/* Port number and IP address taken from servver arguments*/
int port;
char* loggerIP;

static void
part_c_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		inputData part_c_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *,char *, int);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case part_c:
		_xdr_argument = (xdrproc_t) xdr_inputData;
		_xdr_result = (xdrproc_t) xdr_outputData;
		local = (char *(*)(char *, struct svc_req *,char *, int)) part_c_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp, loggerIP, port);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	/* Take Port number and IP address from server arguments*/
	loggerIP = argv[1];
	port = atoi(argv[2]);
	
	register SVCXPRT *transp;

	pmap_unset (PART_C_PROG, PART_C_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PART_C_PROG, PART_C_VERS, part_c_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PART_C_PROG, PART_C_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PART_C_PROG, PART_C_VERS, part_c_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PART_C_PROG, PART_C_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
