/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_B_H_RPCGEN
#define _PART_B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputData {
	char *path;
	char *outfile_name;
	int a;
	int b;
};
typedef struct inputData inputData;

struct outputData {
	int result;
	int error;
	char *error_message;
};
typedef struct outputData outputData;

#define PART_B_PROG 0x12345678
#define PART_B_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define part_b 1
extern  outputData * part_b_1(inputData *, CLIENT *);
extern  outputData * part_b_1_svc(inputData *, struct svc_req *);
extern int part_b_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define part_b 1
extern  outputData * part_b_1();
extern  outputData * part_b_1_svc();
extern int part_b_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputData (XDR *, inputData*);
extern  bool_t xdr_outputData (XDR *, outputData*);

#else /* K&R C */
extern bool_t xdr_inputData ();
extern bool_t xdr_outputData ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_B_H_RPCGEN */
